version: '2'
services:
    arches:
      container_name: arches
      image: archesproject/arches:master
      build:
        context: ./arches
        dockerfile: ./Dockerfile
      command: run_arches
      volumes:
        - ./lincoln:/web_root/lincoln
        - ./arches:/web_root/arches
        - ./arches/docker/settings_local.py:/web_root/arches/arches/settings_local.py
        - lincoln-arches-log:/arches/arches/logs
        - lincoln-packages:/web_root/lincoln/lincoln/media/packages
        - lincoln-node_modules:/web_root/lincoln/lincoln/node_modules
        - lincoln-arches-static:/static_root
        - /arches/temp/:/web_root/import
      environment:
        - ARCHES_PROJECT=lincoln
        - INSTALL_DEFAULT_GRAPHS=True
        - INSTALL_DEFAULT_CONCEPTS=True
        - PGUSERNAME=postgres
        - PGPASSWORD=postgres
        - PGDBNAME=arches
        - PGHOST=db
        - PGPORT=5432
        - COUCHDB_HOST=couchdb
        - COUCHDB_PORT=5984
        - COUCHDB_USER=admin
        - COUCHDB_PASS=password
        - ESHOST=elasticsearch
        - ESPORT=9200
        - ELASTICSEARCH_PREFIX=lincoln
        - DJANGO_MODE=PROD
        - DJANGO_DEBUG=False
        # - DJANGO_REMOTE_DEBUG=False
        - DOMAIN_NAMES=arcade-test.lincoln.gov.uk
        - TZ=UTC
      ports:
        - '8000:8000'
      depends_on:
        - db
        - elasticsearch
        - couchdb

    nginx:
      container_name: nginx
      image: cvast/cvast-nginx:1.2.0
      restart: unless-stopped
      ports:
        - '8088:80'
        - '443:443'
      volumes:
        - lincoln-arches-static:/www/static
        - lincoln-letsencrypt-acme-challenge:/var/www
        - lincoln-letsencrypt:/etc/letsencrypt
      environment:
        - NGINX_PROXY_MODE=local
        - NGINX_PROTOCOL=strict-https
        - LOCAL_PROXY_HOST=arches
        - LOCAL_PROXY_PORT=8000
        - DOMAIN_NAMES=arcade-test.lincoln.gov.uk
        - PUBLIC_MODE=False
        - TZ=UTC
      depends_on:
        - arches

    db:
      container_name: db
      image: mdillon/postgis:9.6-alpine
      volumes:
          - lincoln-postgres-data:/var/lib/postgresql/data
          - lincoln-postgres-log:/var/log/postgresql
      ports:
        - '54322:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=UTC

    couchdb:
      container_name: couchdb
      image: couchdb:2.1.1
      ports:
        - "5984:5984"
      environment:
        - COUCHDB_USER=admin
        - COUCHDB_PASSWORD=password
        - TZ=UTC
      volumes:
        - lincoln-couchdb-data:/usr/local/var/lib/couchdb
        - lincoln-couchdb-log:/usr/local/var/log/couchdb

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:5.2
      volumes:
        - lincoln-elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=UTC

    letsencrypt:
      container_name: letsencrypt
      image: cvast/cvast-letsencrypt:1.1
      volumes:
        - lincoln-letsencrypt-acme-challenge:/var/www
        - lincoln-letsencrypt:/etc/letsencrypt
        - lincoln-letsencrypt-log:/var/log/letsencrypt
      command: get_certificate
      environment:
        - MODE=regular
        - FORCE_RENEWAL=False
        - LETSENCRYPT_EMAIL=mike.campbell@k-int.com
        - DOMAIN_NAMES=arcade-test.lincoln.gov.uk
        - PRODUCTION_MODE=True
        - PERSISTENT_MODE=True
        - TZ=UTC
        - FORCE_NON_ELB=True
        - AWS_DEFAULT_REGION=eu-west

volumes:
    lincoln-arches-log:
#    arches-env:
    lincoln-arches-static:
    lincoln-packages:
    lincoln-node_modules:
    lincoln-couchdb-data:
    lincoln-couchdb-log:
    lincoln-postgres-data:
    lincoln-postgres-log:
    lincoln-elasticsearch-data:
    lincoln-letsencrypt:
    lincoln-letsencrypt-log:
    lincoln-letsencrypt-acme-challenge:
