version: '2'
services:
    arches:
      container_name: arches
      image: archesproject/arches:latest
      build:
        context: ./arches
        dockerfile: ./Dockerfile
      command: run_arches
      volumes:
        - ./lincoln:/web_root/lincoln
        - ./arches:/web_root/arches
        - ./arches/docker/settings_local.py:/web_root/arches/arches/settings_local.py
#        - arches-log:/arches/arches/logs
        - lincoln-packages:/web_root/lincoln/lincoln/media/packages
        - lincoln-node_modules:/web_root/lincoln/lincoln/node_modules
        - arches-static:/static_root
      environment:
        - ARCHES_PROJECT=lincoln
        - INSTALL_DEFAULT_GRAPHS=True
        - INSTALL_DEFAULT_CONCEPTS=True
        - PGUSERNAME=postgres
        - PGPASSWORD=postgres
        - PGDBNAME=arches
        - PGHOST=db
        - PGPORT=5432
        - COUCHDB_HOST=couchdb
        - COUCHDB_PORT=5984
        - COUCHDB_USER=admin
        - COUCHDB_PASS=password
        - ESHOST=elasticsearch
        - ESPORT=9200
        - ELASTICSEARCH_PREFIX=lincoln
        - DJANGO_MODE=DEV
        - DJANGO_DEBUG=True
        # - DJANGO_REMOTE_DEBUG=False
        - DOMAIN_NAMES=localhost
        - TZ=PST
      ports:
        - '8000:8000'
      depends_on:
        - db
        - elasticsearch
#        - couchdb

#    nginx:
#      container_name: nginx
#      image: cvast/cvast-nginx:1.2.0
#      restart: unless-stopped
#      ports:
#        - '8088:80'
#        - '443:443'
#      volumes:
#        - arches-static:/www/static
#        - letsencrypt-acme-challenge:/var/www
#        - letsencrypt:/etc/letsencrypt
#      environment:
#        - NGINX_PROXY_MODE=local
#        - NGINX_PROTOCOL=http
#        - LOCAL_PROXY_HOST=arches
#        - LOCAL_PROXY_PORT=8000
#        - DOMAIN_NAMES=localhost
#        - PUBLIC_MODE=False
#        - TZ=PST
#      depends_on:
#        - arches

    db:
      container_name: db
      image: mdillon/postgis:9.6-alpine
      volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-log:/var/log/postgresql
      ports:
        - '54322:5432'
      environment:
        - POSTGRES_PASSWORD=postgres
        - TZ=PST

    couchdb:
      container_name: couchdb
      image: couchdb:2.1.1
      ports:
        - "5984:5984"
      environment:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: password
      volumes:
        - couchdb-data:/usr/local/var/lib/couchdb
        - couchdb-log:/usr/local/var/log/couchdb

    elasticsearch:
      container_name: elasticsearch
      image: elasticsearch:5.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - TZ=PST

#    letsencrypt:
#      container_name: letsencrypt
#      image: cvast/cvast-letsencrypt:1.1
#      volumes:
#        - letsencrypt-acme-challenge:/var/www
#        - letsencrypt:/etc/letsencrypt
#        - letsencrypt-log:/var/log/letsencrypt
#      command: get_certificate
#      environment:
#        - MODE=regular
#        - LETSENCRYPT_EMAIL=info@example.com
#        - DOMAIN_NAMES=localhost
#        - PRODUCTION_MODE=False
#        - PERSISTENT_MODE=True
#        - TZ=PST

volumes:
    arches-log:
    arches-env:
    arches-static:
    lincoln-packages:
    lincoln-node_modules:
    couchdb-data:
    couchdb-log:
    postgres-data:
    postgres-log:
    elasticsearch-data:
#    letsencrypt:
#    letsencrypt-log:
#    letsencrypt-acme-challenge:
