version: '2'
services:
    db:
      container_name: archesdb
      image: kartoza/postgis:12.1
      volumes:
          - postgres-data:/var/lib/postgresql
          - postgres-log:/var/log/postgresql
      ports:
        - '54322:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=postgis
        - POSTGRES_DBNAME=lincoln
        - POSTGRES_TEMPLATE_EXTENSIONS=true
        - TZ=UTC

    elasticsearch:
      container_name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
      volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - discovery.type=single-node
        - TZ=UTC

volumes:
    postgres-data:
    postgres-log:
    elasticsearch-data:
